### ISSUE TITLE
Trims don't save

### ISSUE THREAD

**Issue by losikid** [semerad/gt3b#4]
After radio is power off, my trims do not change, via trim menu. Sub trims do however. I know i'm not the only one as others are whom made me aware of this issue,

Is this meant to be this way? Best i can come up with is because they're supposed to be temp trims...but then again why not save them?

**Comment by semerad** [comment]
> After radio is power off, my trims do not change, via trim menu. Sub
> trims do however. I know i'm not the only one as others are whom made
> me aware of this issue,
> 
>   This is BUG, but trim value is actually saved. Problem is with functions,
> which are mapped to some trims keys. During initialization (PowerOn,
> model change, after key-mapping edit) are MOMentary trims/keys set to
> default values. But there is probably some mistake in the code that
> non-momentary (such as those trims) are set to defaults also. I will
> look at it, this was introduced at version 0.3.0 after that bigger
> key-mapping changes.

**Comment by semerad** [comment]
> After radio is power off, my trims do not change, via trim menu. Sub
> trims do however. I know i'm not the only one as others are whom made
> me aware of this issue,

  OK i found it. There was one mistake that also config values (as are
trims) were set to default (0 for trims) value when applying initial
key mappings. I changed it that this applies only for non-config values
now (as channel-value, DIG-mix, 4WS-mix, ...).
  It will be at next release, which will be 0.4.0, because I added
something more to model config (servo speed for all channels).
