### ISSUE TITLE
Compile errors - invalid narrow pointer cast

### ISSUE THREAD

**Issue by rickeboy** [semerad/gt3b#7]
Hi there!

Thanks for your effort semerad, I just order the GT3b and found that your firmware. Also ordered the STM8S-Discovery (been using Atmels AVRs for some time and always fun to test new micros).

Any ways, got all the ST software and also the Cosmic C compiler... created a new project and loaded all the C and H files.
I havent read them all just trying to compile it and gets the error supplied. Using IdeaSTM8 v5.3.0 and Cosmic STM8 C Cross Compiler v4.3.7.

Getting errors in files eeprom.c: 160
    // FLASH second
    cnt = CONFIG_MODEL_MAX_FLASH;

menu.c:238
    _model = (u8)menu_change_val((s16)_model, 0,
                     MIN(CONFIG_MODEL_MAX, 80) - 1,
                     MODEL_FAST, 1);

task.c:46
 *(u16 *)stack_ret = (u16)function;

And the error I am getting is "invalid narrow pointer cast"...

I obviously think I can use this STM8 compiler if its another chip in the GT3b I am sorry for taking up your time.

Thanks in advance...

//rickeboy

**Comment by semerad** [comment]
> Hi there!
> 
> Thanks for your effort semerad, I just order the GT3b and found that your firmware. Also ordered the STM8S-Discovery (been using Atmels AVRs for some time and always fun to test new micros).

  I am using AVRs also. :-)

> Any ways, got all the ST software and also the Cosmic C compiler... created a new project and loaded all the C and H files.
> I havent read them all just trying to compile it and gets the error supplied. Using IdeaSTM8 v5.3.0 and Cosmic STM8 C Cross Compiler v4.3.7.
> 
> And the error I am getting is "invalid narrow pointer cast"...
> 
> I obviously think I can use this STM8 compiler if its another chip in the GT3b I am sorry for taking up your time.

  Yes, You are using right compiler, but probably with bad settings. Try
to run script "compile.bat" (it is needed to set variable TOOLSET to
path to compiler binaries before) and see if it works.
  It will be needed to set apropriate parameters to IdeaSTM8 then. But I
will not help with this because I am not using it (look at compile.bat
and compile.lkf for compiler and linker parameters).

Pavel Semerad

**Comment by rickeboy** [comment]
Hi Pavel!

I tried the script before I tested the IdeaSTM8 software but run into problems with the fact that i have the folders "Program Files" and "My Documents" => space in the directorynames, not liked by the script and not good as args for the compiler.

Anyways I copied the project and also the cosmic compiler to C:\ and also "hard coded" the TOOLSET and CHANNEL vars in the compile.bat file and it WORKED... stupid spaces in directorynames. Not enjoying the fact that I can't compile in the IDE. Will try to fix the settings and if I manage I will post the settings here...

Thanks again!

Regards,
Rikard Eggers

**Comment by rickeboy** [comment]
Hi again,

By the way Pavel do you use for development? The compile.bat files only?

Regards,
Rikard

**Comment by semerad** [comment]
> Hi again,
> 
> By the way Pavel do you use for development? The compile.bat files only?

  No, this is only easy way for others to compile it (but I didn't know
about that problem with spaces, because on windows I usualy install
software to c:\sw).
  I am developing it at linux, using "vim" as editor and using some older
cosmic C compiler which I run under "wine". And then using Makefile-s
which do the compile and dependency work (Makefile-s You can see at
sources).
  But if You will create configuration for some IDE, I can include it
at sources for others.

Pavel Semerad

**Comment by rickeboy** [comment]
Aahh... I see... well I also run Linux (Debian) but I installed WinXP on an old laptop to get this ST stuff running because I have used Wine but without any success.

I have gotten ST Visual Develop to work and the stm8_interrupt_vector.c is got me some headache... but renaming the vector.c to stm8_interrupt_vector.c got that to work but now I am getting 
#error clnk Debug\gt3b.lkf:1 segment .text size overflow (12617)

Thoose ST people really havent made this things plug-and-play ;)

The compiler.bat file works... will use that way for know and try a bit more with the IDE:s...

Thanks again... :)

Rikard

**Comment by semerad** [comment]
> Aahh... I see... well I also run Linux (Debian) but I installed WinXP on an old laptop to get this ST stuff running because I have used Wine but without any success.

  I have WinXP in VirtualBox at linux to run STVP and STVD, because it
doesn't run under wine.

> I have gotten ST Visual Develop to work and the stm8_interrupt_vector.c is got me some headache... but renaming the vector.c to stm8_interrupt_vector.c got that to work but now I am getting 
> #error clnk Debug\gt3b.lkf:1 segment .text size overflow (12617)

  I am using STVD only for debugging so I don't run compiler from it and
don't understand how this error was done.

> Thoose ST people really havent made this things plug-and-play ;)

  Maybe I did it incompatible with ST tools :-) . It was easier for me to
use Makefiles as I always did before.

> The compiler.bat file works... will use that way for know and try a bit more with the IDE:s...

  I think that with some tweaking it will be possible to use Makefiles
under cygwin at windows.

Pavel

**Comment by rickeboy** [comment]
Hehe... maybe you did ... Will try the debugging but wont put more time on getting the IDE compiler to run... already put quite some effort into it. Will live with the compile.bat file for now...

Rikard
